# Define a Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl # Name of the Deployment
spec:
  replicas: 1 # Number of pod replicas to run
  selector:
    matchLabels:
      app: payments # Select pods with the label 'app: payments'
  template:
    metadata:
      labels:
        app: payments # Apply the label 'app: payments' to the pods created by this template
    spec:
      containers:
        - name: payments # Name of the container
          image: comauro7511/payments # Docker image to use for this container
          env:
            - name: NATS_CLIENT_ID # Environment variable to set the NATS client ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL # Environment variable to set the NATS URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID # Environment variable to set the NATS cluster ID
              value: ticketing
            - name: MONGO_URI # Environment variable to set in the container
              value: 'mongodb://payments-mongo-srv:27017/payments'
            - name: JWT_KEY # Environment variable to set in the container
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # Reference to the Kubernetes Secret named 'jwt-secret'
                  key: JWT_KEY # The key in the Secret to use for this environment variable
            - name: STRIPE_KEY # Environment variable to set in the container
              valueFrom:
                secretKeyRef:
                  name: stripe-secret # Reference to the Kubernetes Secret named 'jwt-secret'
                  key: STRIPE_KEY # The key in the Secret to use for this environment variable

---
# Define a Service
apiVersion: v1
kind: Service
metadata:
  name: payments-srv # Name of the Service
spec:
  type: ClusterIP # Service type; ClusterIP exposes the Service on a cluster-internal IP
  selector:
    app: payments # Select pods with the label 'app: payments'
  ports:
    - name: payments # Name of the port
      protocol: TCP # Protocol to use
      port: 3000 # Port on which the Service is exposed
      targetPort: 3000 # Port on the pod that the Service should forward traffic to
